version: '3'
services:
  #Nginx Service
  webserver:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - laravel-network

  #PHP Service
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: app
    user: "1000:1000"
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/config/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: dblaravel
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: passwd
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/:/etc/mysql/
    networks:
      - laravel-network

#Docker Networks
networks:
  laravel-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
